print(" *** Number Fun !!! ***")
a,b = input("Enter a b : ").split()
print("a=",a,"\ttype =",type(a))
print("b=",b,"\ttype =",type(b))
a = int(a)
b = int(b)
print("a/b = %.2f"%(a/b))
print("b/a = %.3f"%(b/a))
print("a/b =",a//b,"r",a%b)
print("b/a =",b//a,"r",b%a)