print(" *** Integer division ***")
x = input("Enter a 3-digit number : ")
print(x, type(x))
x = float(x)
print(x,type(x))
x = int(x)
print(x, type(x))
print("divided by 25 =",x/25)
print("divided by 25 =",x//25," remainder = ", x%25)
print("tenth-digit =",x//10%10)